[package]
name = "large-primes"
version = "0.1.0"
edition = "2024"

[dependencies]
glass_pumpkin = "1.7.0"
num-bigint = "0.4.6"
num-integer = "0.1.46"
num-prime = "0.4.4"
num-traits = "0.2.19"
num_cpus = "1.16.0"
rand = "0.8.0"
rayon = "1.10.0"

